services:
  - type: web
    name: ecommerce-backend
    env: node
    plan: free
    buildCommand: cp -r backend/* /opt/render/project/src/ && cd /opt/render/project/src && npm install --production
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
    buildFilter:
      paths:
        - backend/**/*
    dockerCommand: apt-get update -y && apt-get install -y chromium
    startCommand: node /opt/render/project/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
  
  - type: web
    name: ecommerce-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run install-frontend && npm run build-frontend
    staticPublishPath: ./build