services:
  - type: web
    name: ecommerce-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && cd dist
    startCommand: cd dist && node index.js
    envVars:
      - key: NODE_ENV
        value: production
  
  - type: web
    name: ecommerce-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run install-frontend && npm run build-frontend
    staticPublishPath: ./build