services:
  - type: web
    name: ecommerce-backend
    env: node
    plan: free
    buildCommand: |
      apt-get update -y && 
      apt-get install -y chromium chromium-common chromium-sandbox && 
      cp -r backend/* /opt/render/project/src/ && 
      cp backend/package*.json /opt/render/project/src/ && 
      cd /opt/render/project/src && 
      npm install --production
    startCommand: node /opt/render/project/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
  
  - type: web
    name: ecommerce-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run install-frontend && npm run build-frontend
    staticPublishPath: ./build