services:
  - type: web
    name: ecommerce-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --build-from-source=sqlite3
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production